### ISSUE TITLE
Contact us page times out

### ISSUE THREAD

**Issue by roexian** [neotsn/tsn8#10]
Issue: When submitting a contact us message the page times out.

Page: https://the-spot.net/phorums/memberlist.php?mode=contactadmin

Error message:
SQL ERROR [ mysql4 ]
MySQL server has gone away [2006]
An SQL error occurred while fetching this page. Please contact the Board Administrator if this problem persists.

**Comment by neotsn** [comment]
This was resolved by correcting the email settings in the phpBB board configuration. Apparently the authentication method was incorrect (Login instead of Plain) and causing (what I assume was) a 500 Internal Server Error, making everything else timeout.
