### ISSUE TITLE
Cant reset password

### ISSUE THREAD

**Issue by roexian** [neotsn/tsn8#6]
On https://the-spot.net/phorums/ucp.php?mode=sendpassword 

When resetting password it runs for 30 seconds and gives this error message.

SQL ERROR [ mysql4 ]
MySQL server has gone away [2006]
An SQL error occurred while fetching this page. Please contact the Board Administrator if this problem persists.

**Comment by neotsn** [comment]
This is a difficult one - I'm not sure how to fix it. It happens when the queries take too long, and phpbb's queries are notoriously hodge-podged php constructs. I might able to change a mysql timeout settings somewhere.

**Comment by neotsn** [comment]
See the resolution on #10 - improper email authentication settings for board configuration.
