### ISSUE TITLE
Header Logo Link

### ISSUE THREAD

**Issue by roexian** [neotsn/tsn8#8]
Set the header logo to link back to main part of tsn forums page.

**Comment by neotsn** [comment]
i attempted to do this, but it broke the search container for some reason. I'll have to look into the way it is being styled, and why it would care what is going on with its parent. It might just be a browser rendering issue, and require a more proper html structure.

**Comment by neotsn** [comment]
Fixed. Required an absolute positioning of the search box, since an a-tag can't be inside another a-tag and the advanced search button is an a-tag...causing it to split off from the rest of the search box.
